name: Desafio

on: push

jobs:
  pushlish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT
        run: pwd && ls -la
      - name: Deploy to desafio1.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'desafio1.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}