name: Desafio

on: push

jobs:
  pushlish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to jogo-da-velha.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'jogo-da-velha.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}